# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "lychee"
type = "cli"

[platform.macos]
download-file = "lychee-arm64-macos.tar.gz"

[platform.linux]
download-file = "lychee-{arch}-unknown-linux-{libc}.tar.gz"

[platform.windows]
download-file = "lychee-x86_64-windows.exe"

[install]
download-url = "https://github.com/lycheeverse/lychee/releases/download/lychee-v{version}/{download_file}"

[install.arch]
x86_64 = "x86_64"
arm64 = "arm"
aarch64 = "aarch64"

[resolve]
git-url = "https://github.com/lycheeverse/lychee"
version-pattern = "^lychee-v((?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+))"
